name: Run Python Script

on:
  #push:
  #  branches:
  #    - github-action-test
  #pull_request:
  
  #  branches:
  #    - main
  schedule:
    - cron: '35 11 * * 1-5' # At 01 20 PM GMT on Monday - Friday
  workflow_dispatch:
    inputs:
      branch:
        description: 'dsum daily order improvements'
        required: true
        default: 'github-action-test'
    
jobs:
  run-python-script:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      
      - name: Install dependencies
        run: |
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          fi
      
      - name: Run Python script
        run: python3 python/helloworld.py  # Change 'script.py' to your actual script filename
